#:schema node_modules/wrangler/config-schema.json
name = "dotfolder"
main = "dist/_worker.js/index.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "folder-db"
database_id = "e9a9fd08-a1c0-4222-8c7a-56cf5b984d6d"

[env.staging]
name = "folder-staging"
compatibility_flags = ["nodejs_compat"]

[env.staging.assets]
directory = "./dist"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "folder-db"
database_id = "placeholder-replace-with-real-id"
